DTO
pmm-gwo/budgetcalculator pull request #4
Opened 2023-02-03 18:35 UTC by pmm-gwo

Mapping with MappStruct

2023-02-05 20:35 UTC, nitekm requested changes

2023-02-05 20:35 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/controller/ExpenseController.java
>      @DeleteMapping("/{id}")
Maybe I didn't mention it before, but delete method should not return ResponseEntity<Expense> rather <Void>

2023-02-05 20:35 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/controller/ExpenseTypeController.java
Same as expense controller delete -> ResponseEntity<Void>

2023-02-05 20:35 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/entity/dto/BaseEntityDto.java
> +public class BaseEntityDto {
Where is rest of fields from BaseEntity? Version? CreatedDate?

2023-02-05 20:35 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/entity/dto/BaseEntityDto.java
> +    @Id
DTO is not DB entity it does not need @Id. @Id means this field is primary key for related database table. Everytime you use some adnotation ask yourself what does it do and do i really need it here.

2023-02-05 20:35 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/entity/dto/ExpensePlanDTO.java
> +public class ExpensePlanDTO {
Sometimes there is data, sometimes data, noargs, builder, allargs... So what should it be?

2023-02-05 20:35 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/entity/dto/ExpensePlanDTO.java
> +public class ExpensePlanDTO {
Also most of classes are called xxxDto and this one is xxxDTO. Please use 1 convention

2023-02-05 20:35 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/entity/mapper/ExpenseCategoryMapper.java
> +    List<ExpenseCategoryDto> entityListToDtoList(List<ExpenseCategory> expenseCategoryList);
Mapping list to listDto is redundant. Iterating on list and mapping each element is acceptable and way to go

2023-02-05 20:35 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/entity/mapper/ExpenseCategoryMapper.java
> +    List<ExpenseCategory> dtoListToEntityList(List<ExpenseCategoryDto> expenseCategoryDtoList);
same as above

2023-02-05 20:35 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/entity/mapper/ExpenseCategoryMapper.java
> +    ExpenseCategoryDto entityToDto(Expense expense);
What does it do? How do we map expense to expense category?

2023-02-05 20:35 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/entity/mapper/ExpenseTypeMapper.java
> +    List<ExpenseTypeDto> entityListToDtoList(List<ExpenseType> expenseTypeList);
Mapping list to listDto is redundant. Iterating on list and mapping each element is acceptable and way to go

2023-02-05 20:35 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/entity/mapper/ExpenseTypeMapper.java
> +    List<ExpenseType> dtoListToEntityList(List<ExpenseTypeDto> expenseTypeDtoListList);
same as above

2023-02-05 20:35 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/entity/Expense.java
> +//    @NotBlank(message = "this field is mandatory")
Why validation was removed?

2023-02-05 20:35 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/entity/Expense.java
> +    @JsonManagedReference
Remove this adnotation and include it with DTO with proper mapping in mapper via mapstruct.

2023-02-05 20:35 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/entity/Expense.java
> +    @JsonBackReference
Same as above

2023-02-05 20:35 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/entity/Expense.java
> +//    @NotNull(message = "this field is mandatory")
If something is not needed - remove it instead of comment it out. Keep code clean

2023-02-05 20:35 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/entity/ExpenseCategory.java
> +    @JsonManagedReference
See expense class comments

2023-02-05 20:35 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/entity/ExpenseCategory.java
> +    @JsonManagedReference
See expense class comments

2023-02-05 20:35 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/entity/ExpensePlan.java
> +    @JsonBackReference
See expense class comments

2023-02-05 20:35 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/entity/ExpenseType.java
> +    @JsonBackReference
See expense class comments

2023-02-05 20:35 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/entity/ExpenseType.java
>  //    @JoinTable(
Trash

2023-02-05 20:35 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/exeption/ExpenseCategoryNotFoundException.java
> +public class ExpenseCategoryNotFoundException extends RuntimeException {
This is quite unnecessary. Given you will have 100 entities or even 10000 - will you create xxxNotFoundException for each one? What about some generalization or abstraction? EntityNotFound maybe...?

2023-02-05 20:35 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/repository/ExpenseCategoryRepository.java
> +    ExpenseCategory getExpenseCategoryById(Long id);
Do you need this method if you have findById which does the same thing and return you better type? (Optional)

2023-02-05 20:35 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/service/ExpenseCategoryService.java
> +        return expenseCategoryRepository.findAll().
dot (.) always before statement not after so: findAll() (enter) .stream etc...

2023-02-05 20:35 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/service/ExpenseCategoryService.java
> +        } else throw new ExpenseCategoryNotFoundException(id);
Although is not incorrect there is unwritten contract that java devs always add {} in ifs, elses, try, catches, loop etc.

2023-02-05 20:35 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/service/ExpenseCategoryService.java
> +        } else throw new ExpenseCategoryNotFoundException(id);
Although is not incorrect there is unwritten contract that java devs always add {} in ifs, elses, try, catches, loop etc.

2023-02-05 20:35 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/service/ExpenseService.java
> +        return expenseRepository.
dots before statements

2023-02-05 20:35 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/service/ExpenseService.java
> +        return expenseRepository.findById(id).
dots before statements

2023-02-05 20:35 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/service/ExpenseService.java
> +                stream().map(expense -> expenseMapper.entityToDto(expense)).collect(Collectors.toList());
Each statement in separate line

2023-02-05 20:35 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/service/ExpenseService.java
>          } else throw new ExpenseNotFoundException(id);
Although is not incorrect there is unwritten contract that java devs always add {} in ifs, elses, try, catches, loop etc.

2023-02-05 20:35 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/service/ExpenseService.java
>          } else throw new ExpenseNotFoundException(id);
Although is not incorrect there is unwritten contract that java devs always add {} in ifs, elses, try, catches, loop etc.

2023-02-05 20:35 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/service/ExpenseService.java
> +            ExpenseDto expenseDetails = expenseMapper.entityToDto(expense);
There is variable declared here for mapped expense but you do nothing with it, in return you just repeat the same operation.

2023-02-05 20:35 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/service/ExpenseTypeService.java
> +                findAll().
dots after statemenets

2023-02-05 20:35 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/service/ExpenseTypeService.java
> +                map(expenseType -> expenseTypeMapper.entityToDto(expenseType)).
Each statement in separate line

2023-02-05 20:35 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/service/ExpenseTypeService.java
> +                map(expenseType -> expenseTypeMapper.entityToDto(expenseType)).
DOTS!

2023-02-05 20:35 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/service/ExpenseTypeService.java
>          } else throw new ExpenseTypeNotFoundException(id);
{}

2023-02-05 20:35 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/service/ExpenseTypeService.java
>          } else throw new ExpenseTypeNotFoundException(id);
{}

2023-02-05 20:35 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/service/ExpenseTypeService.java
> +            ExpenseTypeDto expenseTypeDetails = expenseTypeMapper.entityToDto(expenseType);
Return variable or return method call. This variable is useless here

2023-02-05 20:35 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/service/ExpenseTypeService.java
> +        return expenseTypeRepository.findAll().stream().map(expenseType -> expenseTypeMapper.entityToDto(expenseType)).collect(Collectors.toList());
Each statement in separate line

2023-02-06 14:44 UTC, pmm-gwo commented on src/main/java/com/pmm/budgetcalculator/expensing/controller/ExpenseController.java
>      @DeleteMapping("/{id}")
so is it possible to return null ?

2023-02-11 20:34 UTC, nitekm commented on src/main/java/com/pmm/budgetcalculator/expensing/controller/ExpenseController.java
>      @DeleteMapping("/{id}")
Don't return null return response entity OK with empty body or without body at all. Method return type should be ResponseEntity<Void>

2023-02-11 20:42 UTC, nitekm approved these changes

2023-02-11 20:42 UTC, merged